  
spring:
  application:
    name: admin-server
server:
  port: 8083
security:
  basic:
    enabled: false
    
logging:
  file:
    name: admin.log
    path: /root/application/logs/admin
  level: 
    root: info
