spring:
  application:
    name: zblog-zipkin
  zipkin:
    base-url: http://localhost:8082
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
  metrics:
    web:
      server:
        auto-time-requests: false
