spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://localhost:8082

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
